// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_mhF5CYzoeb2aLPNSBHTAl2aZX2g7YIs',
    appId: '1:700678116842:web:4de69ba77e3d527d1fce93',
    messagingSenderId: '700678116842',
    projectId: 'mint-app-a7bcf',
    authDomain: 'mint-app-a7bcf.firebaseapp.com',
    storageBucket: 'mint-app-a7bcf.firebasestorage.app',
    measurementId: 'G-L185C28V9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhzWXE9DX81fIuZsoWYIak6pK3feWc8FM',
    appId: '1:700678116842:android:95541c265fc1dfa91fce93',
    messagingSenderId: '700678116842',
    projectId: 'mint-app-a7bcf',
    storageBucket: 'mint-app-a7bcf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANIR1yECdRtGLvUTt6vDR5pRgWjebp1q0',
    appId: '1:700678116842:ios:b097de87be2210981fce93',
    messagingSenderId: '700678116842',
    projectId: 'mint-app-a7bcf',
    storageBucket: 'mint-app-a7bcf.firebasestorage.app',
    iosBundleId: 'com.example.bdProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANIR1yECdRtGLvUTt6vDR5pRgWjebp1q0',
    appId: '1:700678116842:ios:b097de87be2210981fce93',
    messagingSenderId: '700678116842',
    projectId: 'mint-app-a7bcf',
    storageBucket: 'mint-app-a7bcf.firebasestorage.app',
    iosBundleId: 'com.example.bdProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_mhF5CYzoeb2aLPNSBHTAl2aZX2g7YIs',
    appId: '1:700678116842:web:f032ce617379d34b1fce93',
    messagingSenderId: '700678116842',
    projectId: 'mint-app-a7bcf',
    authDomain: 'mint-app-a7bcf.firebaseapp.com',
    storageBucket: 'mint-app-a7bcf.firebasestorage.app',
    measurementId: 'G-8CN7775BTS',
  );
}
