// lib/features/tasks/providers/tag_providers.dart

import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../data/database/app_database.dart';
import '../../../shared/providers/repository_providers.dart';

// ── Stream providers ──────────────────────────────────────────────────────────

/// All tags in the database (for the tag picker).
final allTagsProvider = StreamProvider<List<Tag>>((ref) {
  return ref.watch(taskRepositoryProvider).watchAllTags();
});

/// Tags currently attached to a specific task.
final tagsForTaskProvider =
StreamProvider.family<List<Tag>, String>((ref, taskId) {
  return ref.watch(taskRepositoryProvider).watchTagsForTask(taskId);
});

/// A single task list by ID — used by the list header to get the list name.
final listByIdProvider =
StreamProvider.family<TaskList?, String>((ref, listId) {
  return ref.watch(projectRepositoryProvider).watchListById(listId);
});

// ── Tag notifier ──────────────────────────────────────────────────────────────

final tagNotifierProvider =
AsyncNotifierProvider<TagNotifier, void>(TagNotifier.new);

class TagNotifier extends AsyncNotifier<void> {
  @override
  Future<void> build() async {}

  // ── BUG N1 FIX ─────────────────────────────────────────────────────────────
  // createTag() previously returned Future<void>. The _createTag() method in
  // task_detail_screen.dart had no way to get the new tag's ID and fell back
  // to '' as the tagId, so no tag was ever linked to the task.
  //
  // Fix: return the ID generated by TaskRepository.createTag() so the caller
  // can immediately pass it to addTagToTask() without a follow-up DB query.
  // ─────────────────────────────────────────────────────────────────────────
  Future<String> createTag({
    required String name,
    required String color,
  }) async {
    // We do NOT set state = AsyncLoading here because that would hide the
    // tag picker UI while the insert completes. The operation is fast enough
    // that optimistic updates feel better.
    return ref.read(taskRepositoryProvider).createTag(
      name : name,
      color: color,
    );
  }

  Future<void> addTagToTask({
    required String taskId,
    required String tagId,
  }) async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(
          () => ref.read(taskRepositoryProvider).addTagToTask(
        taskId: taskId,
        tagId : tagId,
      ),
    );
  }

  Future<void> removeTagFromTask({
    required String taskId,
    required String tagId,
  }) async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(
          () => ref.read(taskRepositoryProvider).removeTagFromTask(
        taskId: taskId,
        tagId : tagId,
      ),
    );
  }
}